### ISSUE TITLE
Linked Templates phase 1

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#1116]
# Top Level Features

## P1
- [x] Support relativePath
  - [x] **ISSUE**: Does ARM support this yet?
- [x] **ISSUE**: Support uri? (Download from URI to template file in vscode)
  - [x] If not, make clear to the user
- [x] Load linked templates into vscode automatically
  - [x] Error-handling, e.g. linked template not found, can't load, etc.
- [x] Validation of parameters
  - [x] Should be able to easily determine the cause and location of error
  - [x] Parameter missing
  - [x] Extra parameter
  - [x] Type mismatch
    - [x] **ISSUE**: Passing an incorrect parameter value doesn't tell which parameter or its location
- [x] Snippet
  - [x] Use relativePath for default snippet instead of uri
  - [x] **ISSUE**: Is there a single snippet or two separate ones? 
- [x] Intellisense for parameters
  - [x] Parameter completion (when typing inside the "parameters" object)
    - [x] [IN PROGRESS] BUG: Adding optional parameter values doesn't work
  - [x] Light bulb: Add all missing parameters
    - [x] [IN PROGRESS] BUG: Adding optional parameter values doesn't work
  - [x] Light bulb: Add required missing parameters
  - [x] Fill in with value from main template's parameter of the same name, e.g.:
``` 
"parameters": {
        "intParam": {
            "type": "int",
            "value" : "[parameters ( 'intParam' )]"
        }
    },
```
- [x] Make clear to users when full validation is off
  - [x] Give message when full validation is off that we can't validate the linked template without it
  - [x] Do the same for nested templates -> https://github.com/microsoft/vscode-azurearmtools/issues/1190
- [x] Performance
  - [x] **ISSUE**: Is start-up performance an issue? (no worse than previous version, but still slow - 1min)
  - [x] **ISSUE**: Don't think it was always this slow.  When did it regress?
- [x] Automatically revalidate when linked file changes
  - [x] Changes on disk
  - [x] Changes in vscode (unsaved)
  - [x] File created or deleted
  - [x] BUG?: Language server doesn't request file again when file doesn't exist then is created
    - [x] One behavior this causes is that a new file won't change the "file not found" error until it is marked as arm-template
  - [x] Bug: Stuck on loading?
  - [x] Need a refresh button in code lens?
- [x] **ISSUE**: UI needs finalization
  - [x] Full validation on/off
    - [x] don't show validation on message
  - [x] Indicate when linked template is successfully loaded/validation?
  - [x] Give message for uri's that we don't support them yet?
  - [x] Show linked template resolved path
  - [x] Where show code lens? Show editor decoration instead?
    - [x] Answer: Show decoration outside resource but code lens by templateLink
  - [x] Do we show "(loaded)"?
- [x] [IN PROGRESS] Show the relativePath value as a link (clicking on it would navigate to the template
- [x] Telemetry -> https://github.com/microsoft/vscode-azurearmtools/issues/1192
- [x] Handle multiple linked template references in main template (to same or different linked templates)
- [x] Handle linked references in a copy loop
- [x] Cache linked template tree to avoid spurious behavior -> https://github.com/microsoft/vscode-azurearmtools/issues/1189
- [ ] **ISSUE** Show a warning if using relativePath but apiVersion is too small?
## Bugs
- [x] Referencing empty linked template file (no ARM schema), code lens will show "Loading…"
  - [x] This repros whenever the child template is not loaded with langid arm-template.  What do we do?
  - [x] I've seen this in some other scenarios, too...  Especially loading from scratch?
- [x] contentVersion for linked/nested templates should be matched against the linked/nested template, not the main template #1145
- [x] If child template's name differs in casing, loading gets stuck -> https://github.com/microsoft/vscode-azurearmtools/issues/1191
- [x] Empty child template doesn't cause error in main template

**Comment by StephenWeatherford** [comment]
This was released on Monday.  Let us know if you're still having problems, thanks.
