### ISSUE TITLE
Parameter files: Auto-complete missing parameters, link with template for references, renames, etc

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#566]

**Comment by StephenWeatherford** [comment]
## Development notes
- [x] Add menu items, restrict them to JSON files with the params schema
- [x] Open Template menu
- [x] Press double-quote -> “new parameter” completion (always)
- [x] If associated with a template file:
  - [x] Show associated template in status bar
  - [x] press double-quote -> completion for all params from template that don’t have a value
  - [x] Show an error in params file (on “parameters”) if there are missing required params
  - [x] Show quick fix for missing required parameters
  - [x] Show lightbulb for filling in all missing parameters
  - [x] Automatically add a comma before or after as necessary (handle comments in between)
  - [x] If there’s a default value, it becomes the “value” property in params file, otherwise a TODO comment is added (causes an error because comments not allowed)

# Spec questions
- [ ] Do we want a Select Template… in context menu/status bar?  Currently I left it out because I’m not sure if it’s helpful or confusing (and requires more UI work)
- [x] What order insert parameters? (go by order in the template file)
- [ ] Context menu for adding all/required missing parameters parameters (right now just in quick fixes and intellisense)
- [ ] Stop showing parameter file in side-by-side view?  Try to be smarter? Shouldn't open side to side if already in another column.  Shouldn’t show side by when showing template from param file?
- [ ] Put “Browse…” and “New…” higher in the quick pick list?

# P2 work items
- [ ] Select Template…?  (see spec questions)
- [ ] Don’t put default value into param file if it’s an expression (https://github.com/microsoft/vscode-azurearmtools/issues/534)
- [ ] Use editor tab settings
- [ ] Show References in template or params file should show uses/definition from in associated file (https://github.com/microsoft/vscode-azurearmtools/issues/518)
- [ ] Show References on params in template file - show parameter value in params file
- [ ] Rename parameter in template or params file should rename in associated file (https://github.com/microsoft/vscode-azurearmtools/issues/516)
- [ ] Display params file in tree view (https://github.com/microsoft/vscode-azurearmtools/issues/509)
