### ISSUE TITLE
Feature: Support validation and parameter intellisense for linked templates

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#588]
NOTE: The spec info in this bug is out of date, but the feature is mostly implemented.
Remaining work to consider for later has been moved to https://github.com/microsoft/vscode-azurearmtools/issues/1211

## P2

- [x] **ISSUE** Keep it from being closed by vscode after 3 min?? – errors will disappear in the linked template after 3 min
- [x] Support linked parameter files -> #1211
- [x] UTF-8 paths -> #1211
- [x] Spaces in paths
- [x] Path case insensitivity
- [x] **ISSUE**: Linked parameters don&#39;t get validated (and we don&#39;t show linked template info) if there are any other validation errors
- [x] Show linked templates in ARM Template Outline -> #1211
- [x] **ISSUE**: COPY loops show multiple times in UI
- [x] Light bulb: Add missing parameters when there is no "parameters" object in the deployment resource -> #1211

## Later
- [x] Open linked template file with the actual set of parameter values that would be passed in -> #1211

TODO: Update this section

# Spec notes
In scope: literal URIs and relative URIs
- Tooling for the relative path experience will provide the most customer value and is the scenario that we should optimize for

### Validation assembly
https://github.com/microsoft/vscode-azurearmtools/issues/745 Validation API changes to support linked template validation
### Extension work
https://github.com/microsoft/vscode-azurearmtools/issues/1116 Linked Templates phase 1

## Spec Issues
- [x] Need relative path spec from @Alexander Frankel and availability date
- [x] Won't find any linked templates if full validation not enabled
  - [x] Turn on full validation if all parameters have values #512
  - [x] Show information diagnostic if full validation is off
  - [x] CUT #704 - provide dummy value if appropriate
- [x] Won't find second linked template if first has an error
- [x] What's the intellisense/rename/completion experience inside a linked template as far as parameters/outputs go?
  - [x] e.g. if you rename a parameter in a linked template, does it rename it in the parent template's deployment for that linked template? -> https://github.com/microsoft/vscode-azurearmtools/issues/1211
- [x] Editing experience for outputs?  No - that would be an experience for the reference() function's return value
- [x] What's the experience when a linked path can't be found?
  - [x] A: Place an error in the Issues list
- [x] Re-evaluate when linked template file changes - how?
- [x] Handle deployment()?  Right now we return http://fake
  - eg "uri": "[uri(deployment().properties.templateLink.uri, 'static-public-ip.json')]"
    - cannot open https://fake/static-public-ip.json. Detail: Unable to resolve resource https://fake/static-public-ip.json
- [x] How show progress during load phase?
 
Template URI:
We will handle both relative and absolute URIs
 
Validation:
 
Download and buffer template (do we open in tab or not?)
If required parameters are defined in template A, or a parametersLink exist, provide full validation on buffered template (can we do the first part of this?).
Provide schema and expression validation on buffered template.
Error message with line and location from buffered template but provide no navigation to the location.
 
Authoring Experience:
 
Template A parameter completion for template B. Can we also identify required vs optional in the completion experience?
Template A output completion from template B
 
Relative Path:
 
Validation:
 
Open template B from specified path
If required parameters are defined in template A, or a parametersLink exist, provide full validation on template B (can we do the first part of this?).
Provide schema and expression validation on template B.
Error message with line and location from buffered template and potential to provide navigation to the location.
 
Authoring Experience:
 
Same as with Template URI.
 
Other thoughts:
 
Could we do an insert linked template feature which would take in URI / Path and scaffold out the deployment resource, target. and parameters?
Investigate how this will work when we have linked templates with a depth greater than 2  (A > B > C)
When working with relative / on disk templates is there anything to consider if template B has a parameter file mapping?

**Comment by ishepherd** [comment]
Will relative URIs support this? https://feedback.azure.com/forums/281804-azure-resource-manager/suggestions/17275646-enable-using-local-filesystem-for-linked-templates

(🤞 🤞 🤞 🤞 )

**Comment by alex-frankel** [comment]
We are going to support a new property for nested deployments called `relativePath` to help support this. 

The first place we are going to support `relativePath` is for `template specs`, which we [discussed in some depth at //build](https://youtu.be/UaVCNpD3pvg?t=721) for the first time.

For generic deployments, in the short term, we are going to treat `relativePath` as syntactic sugar for the [uri pattern for generic deployments](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md#deployment-artifacts-nested-templates-scripts) that many customers use today. However, you will still need to stage the files yourself to a public location. At some point, we are going to support packaging up deployments w/ `relativePath` in the same way that we will be packaging up `templateSpecs` using the CLI tools, so that you won't need to worry about staging.

VS code will understand and support the relativePath property as part of this work, but it won't be in the first phase.

**Comment by jdelforno** [comment]
This will be extremely helpful considering GitHub Actions allows the repo to be checked out as is and execute the ARM Templates as a local resource within the Runner. 

Thanks for your efforts, please let me know if you'd like testing done.

**Comment by StephenWeatherford** [comment]
@jdelforno Great to know, thanks!  Probably starting on this next wek.

**Comment by jellebens** [comment]
status? no links in milestoneplan...

**Comment by StephenWeatherford** [comment]
Just released 0.13.0, starting to look at this.  Will probably come in phases, the intention is for this to be milestone 0.15.0, but there is a 0.14.0 release planned which will be some minor features and some bug fixes, with 0.15.0 starting in parallel.

Are there any public repos with examples of how you guys have things set up?  The intention was to start with only supporting relative paths (the new relativePath), which is not in public preview yet, but obviously you guys are not using that yet.

**Comment by jellebens** [comment]
It makes sence that when using devops u publish your arm scripts to a dropfolder as an artifact and deploy them from there without having to upload to a blobstorage first

**Comment by mkulisic** [comment]
> @StephenWeatherford some notes on the relative path implementation.
> 
> ## Implementation
> Adding support for a _relativePath_ field to the _TemplateLink_ object of the _Microsoft.Resources/deployments_ resource type.
> 
> ```
> {
>     "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
>     "contentVersion": "1.0.0.0",
>     "resources": [
>         {
>             "name": "nestedDeployment1",
>             "type": "Microsoft.Resources/deployments",
>             "apiVersion": "2019-10-01",
>             "properties": {
>                 "mode": "Incremental",
>                 "templateLink": {
>                     "relativePath": "./assets/azuredeploy.json"
>                 }
>             }
>         }
>     ]
> }
> ```
> 
> Relative Path fields should always use the local file as the starting point (rather than the root template). The customer can specify this implicitly, or with a prefix like ‘.\’ or ‘\’. The relative path will also support / and \ as folder delimiters.
> 
> ## Examples
> Example directory / file structure:
> 
> * TopLevel\entryTemplate.json ** this is the top-level/parent template for all other deployments
> * TopLevel\commonTemplate.json
> * TopLevel\nestedDir\nestedTemplate.json
> * TopLevel\nestedDir\doubleNesting\doubleNestedTemplate.json
> * inaccessibleTemplate.json
> 
> From entryTempalte.json, commonTemplate.json can be deployed in the following ways:
> 
> ```
> "TemplateLink": { 
>     "relativePath": "commonTemplate.json", 
> } 
>  
> "TemplateLink": { 
>     "relativePath": "./commonTemplate.json", 
> } 
>  
> "TemplateLink": { 
>     "relativePath": "\commonTemplate.json", 
> } 
> ```
> 
> From _entryTempalte.json_, _nestedTemplate.json_ can be deployed in the following ways:
> 
> ```
> "TemplateLink": { 
>     "relativePath": " nestedDir\nestedTemplate.json ", 
> } 
> 
> "TemplateLink": { 
>     "relativePath": " ./nestedDir/nestedTemplate.json", 
> }
> ```
> 
> From _nestedTemplate.json_, the other two files can be deployed like this:
> 
> ```
> "TemplateLink": { 
>     "relativePath": " ..\commonTemplate.json", 
> } 
> 
> "TemplateLink": { 
>     "relativePath": " ./doubleNesting/doubleNestedTemplate.json", 
> } 
> ```
> 
> Finally, _inaccessibleTemplate.json_ will not deploy properly, as it is outside the directory of the parent template.
> 
> ## Other considerations
> One of the following will be required in the TemplateLink object, however due to expressiveness limitation of JSON schems, this will not be enforced by a schema.
> 
> ```
> "TemplateLink": { 
>     "uri": <string>, 
>     "id": <string>, 
>     "relativePath": <string>, 
>     "contentVersion": <string>, 
> } 
> ```
> 
> If for example, both `uri` and `relativePath` are specified, the deployment is invalid.
> 
> The validation API will catch this on pre-flight. We will need to consider how / where to put a similar check for the extension. We need to considering bringing this code into the extensions validation code.

Hello, 
I have been trying to use the relativePath on my deployment, but I am running into the following error in my release pipeline: 

"Error Reason: Error: Code=InvalidDeployment; Message=The deployment definition is invalid; TemplateLink RelativePath can only be used with api-version '2020-06-01' or later."

Here is the resource I am trying to deploy (I removed the parameters for privacy): 

`{
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "2020-06-01",
      "name": "[concat(parameters('ProjectName'),'.ADF.', parameters('Environment'))]",
      "subscriptionId": "[parameters('subscriptionId')]",
      "resourceGroup": "[parameters('ResourceGroupName')]",
      "properties": {
        "mode": "Incremental",
        "expressionEvaluationOptions": {
          "scope": "inner"
        },
        "templateLink": {
          "relativePath": "[parameters('ADFTemplateFile')]"
        }
      }

    }`

I am using the correct version of the API, shouldn't this work?

**Comment by StephenWeatherford** [comment]
@mkulisic The new relative path property isn't available publicly yet, it's still in private preview.  cc @alex-frankel

**Comment by stefan-schweiger** [comment]
@StephenWeatherford has there been any update on this? I'm waiting desperately for this 😄

**Comment by StephenWeatherford** [comment]
Been actively working on it (currently OOF).  Hopefully will have something out by end of January.

**Comment by StephenWeatherford** [comment]
See https://github.com/microsoft/vscode-azurearmtools/issues/1116 for first phase.

**Comment by DougalKennedy** [comment]
@StephenWeatherford do you have a link for applying to join the private preview?

**Comment by StephenWeatherford** [comment]
@DougalKennedy I'll be sure to let you know when we have something to test, thanks!

**Comment by MarcusFelling** [comment]
@jdelforno @stefan-schweiger @DougalKennedy We have a new release of ARM Tools for VS Code, that now supports linked template validation. Want to take it for a test drive? You can find the new release here: https://github.com/microsoft/vscode-azurearmtools/releases/tag/v0.15.0-alpha1

We would love your feedback!

**Comment by StephenWeatherford** [comment]
@jdelforno @stefan-schweiger @DougalKennedy I've uploaded alpha2, which supports the "uri" property (alpha1 only supported relativePath).  You can find the release and instructions here: https://github.com/microsoft/vscode-azurearmtools/releases/tag/v0.15.0-alpha2

Don't hesitate to post in our issues with comments or questions, thanks!  I hope to release this next week.

NOTE: This invitation is open to anyone.

**Comment by StephenWeatherford** [comment]
@jdelforno @stefan-schweiger @DougalKennedy 
Alpha 3 (and release candidate): https://github.com/microsoft/vscode-azurearmtools/releases/tag/v0.15.0-alpha3

**Comment by StephenWeatherford** [comment]
Fixed in next release.  Possibly Wednesday.

**Comment by StephenWeatherford** [comment]
This was released on Monday.  Let us know if you have problems os suggestions, thanks!
