### ISSUE TITLE
Snippets: Put under our control (convert snippets to completions)

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#746]
## TODO
- [x] Replace current word
- [x] Handle empty ARM file with arm! snippet
- [x] Shouldn't be adding backslash: "\$schema"
- [x] tab not working
