### ISSUE TITLE
Feature: Code lenses, errors, intellisense and code actions for parameters of nested templates (generalized features from parameter files)

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#770]
## TODOs
- [x] Clicking on value in top-level parameters goes to param file
- [x] Code lens for values for nested inner scoped templates
- [x] Clicking on value in nested template goes to template file
- [x] fix keyvault parameters
- [x] Add missing parameters from f1 not working
- [x] Clicking on keyvault value doesn't go to right place -> https://github.com/microsoft/vscode-azurearmtools/issues/876
- [x] Parameter file behavior in nested templates
  - [x] error param missing
  - [x] code actions
  - [x] Click on "no value found" when no parameters property
- [x] testcases
- [x] Parameter source: parameter file
  - [x] Error loading param file?
  - [x] Error: missing params
  - - [x] Quick fix
  - [x] Add missing parameters
    - [x] What if no "properties"?
  - [x] Top-level parameters
  - - [x] Code lens: current params file
  - - - [x] Click to navigate
  - - [x] Code lens: change params file
  - - [x] Code lens: no param file
  - - [x] Code lens: parameter sources
  - - [x] Code lens: click on parameter source (value, default, not found)
  - - - [x] Error loading param file?
  - - [x] Intellisense for parameter values
- [x] Parameter source: nested deployment
  - [x] Error loading param file?
  - [x] Error: missing params
  - - [x] Quick fix
  - [x] Add missing parameters
    - [x] What if no "properties"?  
Error Message: _span's length must be greater than or equal to 1.
new Issue Language.js:253:9
Object.getMissingParameterErrors getMissingParameterErrors.js:18:13
DeploymentTemplate.getMissingParameterErrors DeploymentTemplate.js:244:65
  - - [x] Code lens: parameter values
  - - [x] Code lens: click on parameter source (value, default, not found)
  - - [x] Intellisense for parameter values
- [ ] Telemetry
